### ISSUE TITLE
Invalid geometry when missing roof attributes

### ISSUE THREAD

**Issue by balazsdukai** [tordanik/OSM2World#121]
If the building is missing the roof attributes the generated geometry is invalid. Appending the `<tag k='roof:shape' v='gabled'/>` tag solves the issue. See #120 

Minimal example: 
[examples_gabled.zip](https://github.com/tordanik/OSM2World/files/909061/examples_gabled.zip)

**Comment by tordanik** [comment]
I belive the problem is due to zero-area triangles in the exported .obj file. At least for me, the building is rendered properly if I remove the following degenerated faces:

```
f 1 1 3 
f 1 3 3 
f 3 3 5 
f 3 5 5 
f 5 5 7 
f 5 7 7 
f 7 7 9 
f 7 9 9 
f 9 9 1 
f 9 1 1
```

Can you confirm that removing these lines from the .obj manually fixes the problem?

If this is indeed the source of the bug, I believe it will be relatively easy for me to modify OSM2World so that it no longer produces these triangles.

**Comment by balazsdukai** [comment]
@tordanik yes, after removing the faces that you listed, the building displays correctly in Blender

**Comment by tordanik** [comment]
The fix outlined above has now been implemented in 547ab5.
