### ISSUE TITLE
local build & download file (src.zip) seems to be corrupted

### ISSUE THREAD

**Issue by JacekTomaszewski** [tordanik/OSM2World#179]
Hello, I have problem with unpacking file http://osm2world.org/download/files/latest/osm2world.zip. Winrar is informing about corrupted file - only "lib" catalog is listed in it. Can you fix this, please?
Or maybe if you can let me know which commit is builded as "OSM2World-latest-bin.zip | 08-Jun-2021 11:13 | 364M |" or how to reproduce that build it in my local environment. I've tried to do it, as in your readme file, with running mvn package. Build is always succesful, but in every build (few random commits in close date to your upload) I have problems with exporting some files. Export is completing but some files are not readable by softwares. When I export the same files with "OSM2World-latest-bin.zip | 08-Jun-2021 11:13 | 364M |" it is always OK and there is no problem with read it by any software. Can you help me with, it? Thanks!

**Comment by tordanik** [comment]
Thanks for reporting this, the zip of the latest build does indeed appear corrupted. I'll make a new one available soon.

**Comment by Discostu36** [comment]
It seems that this issue can be closed? I just successfully downloaded and unpacked osm2world.zip

**Comment by tordanik** [comment]
I believe I've sorted it out now. There were several files involved:
* OSM2World-latest-bin.zip – this is the file linked from the download page, contains the compiled build of OSM2World, and was not corrupted as far as I can tell.
* osm2world.zip – this is not intended for download by the general public, not linked on the website afaik, and only used as an intermediate step in building certain Linux packages. The copy in the correct location was not corrupted, but there was an additional broken copy of this file left over in download/files/latest/ (which is not where that file is supposed to be).

Hope everything is ok now, please let me know if there are still corrupted files somewhere.

@JacekTomaszewski Were you looking for the archive with the source code? I used to publish such an archive, but I no longer do because it's so easy to download a copy of the code directly from GitHub. The latest build at the time of writing is compiled from 88cda1e, so you can go [here](https://github.com/tordanik/OSM2World/tree/88cda1e39dba938934ad5f3adcab6118baa04ba5) and download the code (it's also currently simply the latest commit of the master branch). If that version is giving you problems you didn't have before, that may just be a bug? If so, please report it separately!
