### ISSUE TITLE
Bodies of water cannot be properly isolated in some cases

### ISSUE THREAD

**Issue by KaiKostack** [tordanik/OSM2World#217]
Hello and thank you for this useful program.

I'm having difficulty getting the area of water properly isolated in my example in Baltimore. Not only are the materials not recognized correctly, but there also seems to be a lack of defining geometry, so you can't even correct it manually.

[osm-baltimore.zip](https://github.com/tordanik/OSM2World/files/14948885/osm-baltimore.zip)

![osm-baltimore](https://github.com/tordanik/OSM2World/assets/15039776/9fc269eb-5ab1-4e01-9b6a-0de460213d21)

![result](https://github.com/tordanik/OSM2World/assets/15039776/171f3ab6-74c8-4f19-943c-e438a1725729)

I've made a few attempts with varying coordinates, all of which failed equally. I hope this can be improved.

Best regards,
Kai

**Comment by tordanik** [comment]
The water body is missing because the input data does not contain all members of the [Patapsco River multipolygon relation](https://www.openstreetmap.org/relation/6403751) – only the ones inside the bounding box. Depending on the method you use to obtain OSM input data, there are different options to obtain "complete areas" or "complete multipolygons", but I don't think the osm.org export tool has this ability.

After adding the missing multipolygon members, the result looks like this:
![Screenshot with complete water body multipolygon](https://github.com/tordanik/OSM2World/assets/1270237/6ec41912-e516-4ca9-9a70-3d8fab005a6a)

I've downloaded the missing members by opening your file in [JOSM](https://josm.openstreetmap.de/), selecting one of the ways forming the outer boundary of the water body, right-clicking the relation in its list of relation memberships, and selecting "Download members" or "Download incomplete members". Here's the resulting .osm input file: [osm-baltimore-complete.zip](https://github.com/tordanik/OSM2World/files/14975826/osm-baltimore-complete.zip)

Hope this helps at least a little. I'm closing this issue because I don't think I can fully address this within OSM2World. At least in the general case, it is not possible to unambiguously reconstruct a mutipolygon given only some of its members. Unlike with [natural=coastline](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcoastline), where water is always on the right-hand side of the way, multipolygon members have arbitrary way direction.

**Comment by KaiKostack** [comment]
Thank you for the help and the explanation. I already thought that the water body could be incomplete when exporting the OSM data. Interestingly, it is complete when exporting the map to SVG, which also allowed me to get a coastline. But integrated into the 3D model is of course preferable.

Anyway, does this work with the downloader integrated into OSM2World? I actually think I tried that too, with the same erroneous result. You could implement the missing option there.
