### ISSUE TITLE
Rendering trees' circumference

### ISSUE THREAD

**Issue by ivanbranco** [tordanik/OSM2World#219]
Do you think it could be possible to use circumference=* to better render trees? Currently, tree rendering isn't well-supported in the OSM world, and it would be great to have more support.

Using circumference=* could also help estimate tree sizes ([link](https://github.com/westnordost/streets-gl/commit/00dc531f1e4c0f1f260c7f6d49d61a1bf6fa7104)). Right now, only height=* is used, but measuring tree height is far less simple than measuring their circumference.

**Comment by tordanik** [comment]
Thank you for the suggestion and the link! Yes, this would be reasonably easy to implement – with the limitation that more complex combinations of parameters (e.g. varying trunk diameter and crown diameter independently) would require more sophisticated tree models than what OSM2World is currently using.

It would be straightforward to use circumference to estimate height, and it should also be possible to scale width and height independently if both kinds of tags are provided.

Do you know where the ratios between crown diameter, trunk diameter and height assumed in the linked code come from?

**Comment by westnordost** [comment]
I don't remember.

**Comment by tordanik** [comment]
Since 73c61ad, OSM2World supports `circumference`, `diameter` and `diameter_crown` for trees. This works for individual trees and groups of trees (such as `natural=tree_row`).

If both crown diameter and height are known, both are taken into account to scale the tree horizontally and vertically, respectively. If one of these values is missing, it is estimated based on the other value.

The default trees based on an image texture don't allow varying trunk diameter and crown diameter independently, but the code supports this for models which use 3D geometry instead of textures to represent a tree.
