### ISSUE TITLE
generating traffic signs

### ISSUE THREAD

**Issue by Matthias84** [tordanik/OSM2World#24]
Just an idea and the question, if you could imagine if that would be possible to add:
An algorithm that add street signs shortly after crossings?
1. follow street network
2. trigger if a way splitsup
3. oh it's a footway dedicated to pedestrians and bicyclists
4. pick the right image from Wikipedia depending on country
5. create an pole with the mounted sign shortly below the crossing near the way
6. continue following the road network ...

**Comment by tordanik** [comment]
A first version of this has been implemented as part of #155. It's still quite rudimentary, works only for a few sign types and is disabled by default (because of issues with the signs' location, and a preference for OSM2World to avoid guesswork that cannot be overridden by more precise mapping), but a starting point for this functionality is now available.
