### ISSUE TITLE
inconsistent roof:orientation in slippy map and desktop

### ISSUE THREAD

**Issue by HolgerJeromin** [tordanik/OSM2World#62]
The ridges of the buildings
http://osm.org/browse/way/92243454 (v4) and 
http://osm.org/browse/way/198746879 (v3) are rendered parallel to the street at my deskop software, but perpendicular in 
http://maps.osm2world.org/?h=128&view=W&zoom=18&lat=50.77112&lon=6.07365&layers=B0FFFF

**Comment by tordanik** [comment]
With the [roof:direction](https://wiki.openstreetmap.org/wiki/Key:roof:direction) key now established in OSM and supported by OSM2World, my recommendation is to use it for all buildings with a roughly square or otherwise ambiguous footprint. The interpretation of roof:orientation is going vary not only within OSM2World, but also between different renderers, and should not be relied on.
